# Generated by Django 4.2.7 on 2026-01-04 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_is_archived_clinicalnote_fileattachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentistAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dentist', models.ForeignKey(limit_choices_to={'role__in': ['dentist', ''], 'user_type__in': ['staff', 'owner']}, on_delete=django.db.models.deletion.CASCADE, related_name='date_availability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dentist Date Availability',
                'verbose_name_plural': 'Dentist Date Availabilities',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['dentist', 'date'], name='api_dentist_dentist_e252c2_idx'), models.Index(fields=['date'], name='api_dentist_date_aeb011_idx')],
                'unique_together': {('dentist', 'date')},
            },
        ),
    ]
