# Generated by Django 6.0 on 2026-01-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_dentistavailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentnotification',
            name='notification_type',
            field=models.CharField(choices=[('new_appointment', 'New Appointment'), ('reschedule_request', 'Reschedule Request'), ('cancel_request', 'Cancel Request'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_confirmed', 'Appointment Confirmed'), ('reschedule_approved', 'Reschedule Approved'), ('reschedule_rejected', 'Reschedule Rejected'), ('cancel_approved', 'Cancellation Approved'), ('cancel_rejected', 'Cancellation Rejected')], max_length=30),
        ),
    ]
