# Generated by Django 4.2.7 on 2026-01-05 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_appointmentnotification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentnotification',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_notifications', to='api.appointment'),
        ),
    ]
