# Generated by Django 4.2.7 on 2026-01-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_appointmentnotification_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.IntegerField(default=30, help_text='Duration in minutes'),
        ),
    ]
