# Generated by Django 4.2.7 on 2026-01-26 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_document_appointment_and_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='teethimage',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teeth_images', to='api.appointment'),
        ),
    ]
