# Generated by Django 4.2.7 on 2026-01-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_teethimage_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='teethimage',
            name='image_type',
            field=models.CharField(choices=[('xray', 'X-Ray'), ('intraoral', 'Intraoral'), ('extraoral', 'Extraoral'), ('panoramic', 'Panoramic'), ('dental', 'Dental Image'), ('other', 'Other')], default='dental', max_length=20),
        ),
    ]
