# Generated by Django 4.2.7 on 2026-01-28 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_teethimage_image_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.CharField(blank=True, help_text='Optional reason for blocking', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'user_type__in': ['staff', 'owner']}, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blocked Time Slot',
                'verbose_name_plural': 'Blocked Time Slots',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['date'], name='api_blocked_date_1e322f_idx'), models.Index(fields=['date', 'start_time', 'end_time'], name='api_blocked_date_ad5071_idx')],
            },
        ),
    ]
