# Generated by Django 4.2.7 on 2026-01-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_blockedtimeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('waiting', 'Waiting'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('missed', 'Missed'), ('reschedule_requested', 'Reschedule Requested'), ('cancel_requested', 'Cancel Requested')], default='confirmed', max_length=25),
        ),
    ]
