# Generated by Django 4.2.7 on 2026-01-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_waiting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='color',
            field=models.CharField(default='#10b981', help_text='Hex color code (e.g., #10b981)', max_length=7),
        ),
    ]
