# Generated by Django 4.2.7 on 2026-01-31 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_appointment_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Clinic where appointment occurs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api.cliniclocation'),
        ),
        migrations.AddField(
            model_name='service',
            name='clinics',
            field=models.ManyToManyField(blank=True, help_text='Clinics where this service is offered', related_name='services', to='api.cliniclocation'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_clinic',
            field=models.ForeignKey(blank=True, help_text='Clinic where staff/dentist is currently assigned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='api.cliniclocation'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['clinic', 'date'], name='api_appoint_clinic__a568f0_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['clinic', 'status'], name='api_appoint_clinic__e678e2_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date', 'time'], name='api_appoint_date_c273d7_idx'),
        ),
    ]
