# Generated by Django - Data Migration
from django.db import migrations


def create_main_clinic_and_assign_data(apps, schema_editor):
    """
    Create a default 'Main Clinic' and assign all existing data to it.
    This ensures backward compatibility with existing records.
    """
    ClinicLocation = apps.get_model('api', 'ClinicLocation')
    Appointment = apps.get_model('api', 'Appointment')
    User = apps.get_model('api', 'User')
    Service = apps.get_model('api', 'Service')
    
    # Create Main Clinic if it doesn't exist
    main_clinic, created = ClinicLocation.objects.get_or_create(
        name="Main Clinic",
        defaults={
            'address': "To be updated - Please update clinic address",
            'phone': "0000000000",  # Placeholder
            'latitude': None,
            'longitude': None,
        }
    )
    
    if created:
        print(f"✓ Created Main Clinic (ID: {main_clinic.id})")
    else:
        print(f"✓ Main Clinic already exists (ID: {main_clinic.id})")
    
    # Assign all existing appointments to Main Clinic
    appointments_updated = Appointment.objects.filter(clinic__isnull=True).update(clinic=main_clinic)
    print(f"✓ Assigned {appointments_updated} appointments to Main Clinic")
    
    # Assign all staff and owners to Main Clinic
    staff_updated = User.objects.filter(
        user_type__in=['staff', 'owner'],
        assigned_clinic__isnull=True
    ).update(assigned_clinic=main_clinic)
    print(f"✓ Assigned {staff_updated} staff/owners to Main Clinic")
    
    # Assign all services to Main Clinic (ManyToMany)
    services_without_clinic = Service.objects.filter(clinics__isnull=True)
    for service in services_without_clinic:
        service.clinics.add(main_clinic)
    print(f"✓ Assigned {services_without_clinic.count()} services to Main Clinic")
    
    print("✓ Data migration completed successfully!")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - remove clinic associations
    """
    ClinicLocation = apps.get_model('api', 'ClinicLocation')
    
    # We don't delete the Main Clinic, just clear associations
    # This is safer for rollback scenarios
    print("⚠ Reversing clinic assignments (not deleting Main Clinic)")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_clinic_to_core_models'),
    ]

    operations = [
        migrations.RunPython(
            create_main_clinic_and_assign_data,
            reverse_migration
        ),
    ]
