# Generated by Django 4.2.7 on 2026-02-01 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_assign_existing_data_to_main_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Clinic where this billing was created', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billings', to='api.cliniclocation'),
        ),
        migrations.AddField(
            model_name='dentalrecord',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Clinic where this record was created', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dental_records', to='api.cliniclocation'),
        ),
        migrations.AddField(
            model_name='document',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Clinic where this document was uploaded', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='api.cliniclocation'),
        ),
    ]
