# Generated by Django 4.2.7 on 2026-02-01 02:27

from django.db import migrations


def assign_clinical_data_to_main_clinic(apps, schema_editor):
    """Assign all existing dental records, documents, and billing to Main Clinic"""
    ClinicLocation = apps.get_model('api', 'ClinicLocation')
    DentalRecord = apps.get_model('api', 'DentalRecord')
    Document = apps.get_model('api', 'Document')
    Billing = apps.get_model('api', 'Billing')
    
    # Get or create Main Clinic
    main_clinic, created = ClinicLocation.objects.get_or_create(
        name="Main Clinic",
        defaults={
            'address': "To be updated",
            'phone': "To be updated"
        }
    )
    
    # Assign all dental records to Main Clinic
    dental_records_count = DentalRecord.objects.filter(clinic__isnull=True).update(clinic=main_clinic)
    print(f"Assigned {dental_records_count} dental records to Main Clinic")
    
    # Assign all documents to Main Clinic
    documents_count = Document.objects.filter(clinic__isnull=True).update(clinic=main_clinic)
    print(f"Assigned {documents_count} documents to Main Clinic")
    
    # Assign all billing records to Main Clinic
    billing_count = Billing.objects.filter(clinic__isnull=True).update(clinic=main_clinic)
    print(f"Assigned {billing_count} billing records to Main Clinic")


def reverse_assignment(apps, schema_editor):
    """Reverse the assignment by setting clinic to NULL"""
    DentalRecord = apps.get_model('api', 'DentalRecord')
    Document = apps.get_model('api', 'Document')
    Billing = apps.get_model('api', 'Billing')
    
    DentalRecord.objects.all().update(clinic=None)
    Document.objects.all().update(clinic=None)
    Billing.objects.all().update(clinic=None)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_add_clinic_to_clinical_data'),
    ]

    operations = [
        migrations.RunPython(assign_clinical_data_to_main_clinic, reverse_assignment),
    ]
