# Generated by Django 4.2.7 on 2026-02-02 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_add_clinic_to_availability_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blockedtimeslot',
            new_name='api_blocked_clinic__ee2688_idx',
            old_name='api_blocked_clinic__7f8a3e_idx',
        ),
        migrations.RenameIndex(
            model_name='dentistavailability',
            new_name='api_dentist_clinic__212d3e_idx',
            old_name='api_dentist_clinic__c89e2d_idx',
        ),
    ]
