# Generated by Django 4.2.7 on 2026-02-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_rename_api_blocked_clinic__7f8a3e_idx_api_blocked_clinic__ee2688_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentnotification',
            name='notification_type',
            field=models.CharField(choices=[('new_appointment', 'New Appointment'), ('reschedule_request', 'Reschedule Request'), ('cancel_request', 'Cancel Request'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_confirmed', 'Appointment Confirmed'), ('reschedule_approved', 'Reschedule Approved'), ('reschedule_rejected', 'Reschedule Rejected'), ('cancel_approved', 'Cancellation Approved'), ('cancel_rejected', 'Cancellation Rejected'), ('inventory_alert', 'Inventory Low Stock Alert')], max_length=30),
        ),
    ]
