# Generated by Django 4.2.7 on 2026-02-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_add_inventory_alert_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('waiting', 'Waiting'), ('ongoing', 'Ongoing'), ('done', 'Done')], default='pending', help_text="Patient's current status in clinic workflow", max_length=20),
        ),
    ]
