# Generated by Django 4.2.7 on 2026-02-05 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_appointment_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Clinic where this item is stored', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='api.cliniclocation'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost per unit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='appointmentnotification',
            name='notification_type',
            field=models.CharField(choices=[('new_appointment', 'New Appointment'), ('reschedule_request', 'Reschedule Request'), ('cancel_request', 'Cancel Request'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_confirmed', 'Appointment Confirmed'), ('reschedule_approved', 'Reschedule Approved'), ('reschedule_rejected', 'Reschedule Rejected'), ('cancel_approved', 'Cancellation Approved'), ('cancel_rejected', 'Cancellation Rejected'), ('inventory_alert', 'Inventory Low Stock Alert'), ('inventory_restock', 'Inventory Restocked')], max_length=30),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total cost (unit_cost × quantity)', max_digits=10),
        ),
        migrations.DeleteModel(
            name='ToothChart',
        ),
    ]
