# Generated by Django 4.2.7 on 2026-02-07 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_inventoryitem_clinic_inventoryitem_unit_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, help_text='Format: INV-YYYY-MM-NNNN', max_length=20, unique=True)),
                ('reference_number', models.CharField(db_index=True, help_text='Format: REF-NNNN', max_length=20, unique=True)),
                ('service_charge', models.DecimalField(decimal_places=2, help_text='Charge for the service performed', max_digits=10)),
                ('items_subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Total cost of inventory items used', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Service charge + items subtotal', max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Interest rate per annum (e.g., 10.00 for 10%)', max_digits=5)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, help_text='Calculated interest amount', max_digits=10)),
                ('total_due', models.DecimalField(decimal_places=2, help_text='Final amount due (subtotal + interest)', max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid by patient', max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, help_text='Remaining balance (total_due - amount_paid)', max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('payment_instructions', models.TextField(default='Please pay your overdue amount within 7 days')),
                ('bank_account', models.CharField(default='12345678910', max_length=50)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of invoice', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='quantity × unit_price', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_invoiced', models.DecimalField(decimal_places=2, default=0, help_text='Total amount from all invoices', max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid by patient', max_digits=10)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, help_text='Outstanding balance (invoiced - paid)', max_digits=10)),
                ('last_invoice_date', models.DateField(blank=True, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient Balance',
                'verbose_name_plural': 'Patient Balances',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('waiting', 'Waiting'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('missed', 'Missed'), ('reschedule_requested', 'Reschedule Requested'), ('cancel_requested', 'Cancel Requested')], db_index=True, default='confirmed', max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active_patient',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('staff', 'Receptionist/Dentist'), ('owner', 'Owner')], db_index=True, default='patient', max_length=20),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'status', '-date'], name='apt_patient_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', '-completed_at'], name='apt_completed_at_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['dentist', 'date'], name='apt_dentist_date_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type', 'is_archived'], name='user_type_archived_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type', 'is_active_patient'], name='user_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-created_at'], name='user_created_at_idx'),
        ),
        migrations.AddField(
            model_name='patientbalance',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance_record', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, help_text='Reference to original inventory item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.inventoryitem'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='api.appointment'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='api.cliniclocation'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['patient', '-created_at'], name='inv_patient_created_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', '-due_date'], name='inv_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['clinic', '-created_at'], name='inv_clinic_created_idx'),
        ),
    ]
