# Generated by Django 4.2.7 on 2026-02-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_invoice_invoiceitem_patientbalance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Interest charged for late payments (0 on initial invoice)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Interest rate for late payments (per annum, e.g., 10.00 for 10%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_due',
            field=models.DecimalField(decimal_places=2, help_text='Total amount due (subtotal + interest if overdue)', max_digits=10),
        ),
    ]
