# Generated by Django 4.2.7 on 2026-02-08 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_invoice_interest_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(db_index=True, help_text='Format: PAY-YYYY-MM-NNNN', max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total payment amount received', max_digits=10)),
                ('payment_date', models.DateField(help_text='Date payment was received')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card (Manual)'), ('debit_card', 'Debit Card (Manual)'), ('gcash', 'GCash'), ('paymaya', 'PayMaya'), ('other', 'Other')], default='cash', max_length=20)),
                ('check_number', models.CharField(blank=True, help_text='Check number if payment method is check', max_length=50)),
                ('bank_name', models.CharField(blank=True, help_text='Bank name for checks or transfers', max_length=100)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction/reference number for electronic payments', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the payment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_voided', models.BooleanField(default=False, help_text='Mark payment as voided (cancelled)')),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, help_text='Reason for voiding the payment')),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='api.cliniclocation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of payment allocated to this invoice', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_voided', models.BooleanField(default=False)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_splits', to='api.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='api.payment')),
                ('provider', models.ForeignKey(blank=True, help_text='Dentist who performed the service (for revenue tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_splits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Split',
                'verbose_name_plural': 'Payment Splits',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['payment', 'invoice'], name='paysplit_pay_inv_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['patient', '-payment_date'], name='pay_patient_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['clinic', '-payment_date'], name='pay_clinic_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-payment_date'], name='pay_date_idx'),
        ),
    ]
