# Generated by adding created_by field to Appointment model

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_payment_paymentsplit_payment_pay_patient_date_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                help_text='User who created this appointment',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='created_appointments',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
