# Generated by Django 4.2.7 on 2026-02-11 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_appointment_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('EXPORT', 'Export'), ('ACCESS', 'Access')], db_index=True, help_text='Type of action performed', max_length=20)),
                ('target_table', models.CharField(db_index=True, help_text='Database table/model name affected by the action', max_length=100)),
                ('target_record_id', models.IntegerField(blank=True, help_text='ID of the specific record affected', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the action was performed', null=True)),
                ('user_agent', models.CharField(blank=True, default='', help_text='Browser/client user agent string', max_length=500)),
                ('changes', models.JSONField(blank=True, help_text='Before/after values for modifications. MUST NOT contain passwords or sensitive auth data.', null=True)),
                ('reason', models.TextField(blank=True, default='', help_text='Optional justification for the action')),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action. Null for failed login attempts.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs_created', to=settings.AUTH_USER_MODEL)),
                ('patient_id', models.ForeignKey(blank=True, help_text='Patient whose data was accessed/modified (if applicable)', limit_choices_to={'user_type': 'patient'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs_about', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_timestamp_idx'), models.Index(fields=['actor', '-timestamp'], name='audit_actor_time_idx'), models.Index(fields=['patient_id', '-timestamp'], name='audit_patient_time_idx'), models.Index(fields=['action_type', '-timestamp'], name='audit_action_time_idx'), models.Index(fields=['target_table', 'target_record_id'], name='audit_target_idx')],
            },
        ),
    ]
