# Generated by Django 4.2.7 on 2026-02-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(db_index=True, help_text='Unique identifier for the source page', max_length=255)),
                ('chunk_text', models.TextField(help_text='The text content of this chunk')),
                ('embedding', models.JSONField(default=list, help_text='Embedding vector stored as JSON array of floats')),
                ('page_title', models.CharField(blank=True, default='', max_length=500)),
                ('section_title', models.CharField(blank=True, default='', max_length=500)),
                ('source_url', models.URLField(blank=True, default='', max_length=1000)),
                ('chunk_index', models.IntegerField(default=0, help_text='Order of this chunk within its page')),
                ('token_count', models.IntegerField(default=0, help_text='Approximate token count of chunk_text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Chunk',
                'verbose_name_plural': 'Page Chunks',
                'ordering': ['page_id', 'chunk_index'],
                'indexes': [models.Index(fields=['page_id', 'chunk_index'], name='pagechunk_page_idx'), models.Index(fields=['created_at'], name='pagechunk_created_idx')],
            },
        ),
    ]
