# Generated by Django 4.2.7 on 2026-02-24 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_pagechunk_embedding_pgvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='availability_slot',
            field=models.ForeignKey(blank=True, help_text='The verified availability slot this appointment was booked against. Required for all new bookings to prevent hallucinated appointments.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booked_appointments', to='api.dentistavailability'),
        ),
        migrations.AlterField(
            model_name='pagechunk',
            name='embedding',
            field=models.JSONField(default=list, help_text='Embedding vector stored as JSON array of floats'),
        ),
    ]
