# Generated by Django 4.2.7 on 2026-02-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_service_patient_bookable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_privacy_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the user accepted the Privacy Policy', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='accepted_terms_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the user accepted the Terms & Conditions', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='policy_version',
            field=models.CharField(default='1.0', help_text='Version of the policy documents the user consented to', max_length=50),
        ),
    ]
