# Generated by Django 4.2.7 on 2026-02-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_remove_user_address_user_address_barangay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagechunk',
            name='embedding',
            field=models.JSONField(blank=True, default=None, help_text='Embedding vector stored as JSON array of floats (pgvector on Supabase)', null=True),
        ),
    ]
